# Generated by Django 3.1.6 on 2021-11-29 04:48

from django.db import migrations, models
import mdeditor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(null=True, upload_to='uploads/image/%Y/%m/%d', verbose_name='封面')),
                ('name', models.CharField(max_length=100, verbose_name='授课标题')),
                ('teacher', models.CharField(max_length=20, verbose_name='授课者姓名')),
                ('classes', models.CharField(max_length=100, verbose_name='培训内容分类')),
                ('content', mdeditor.fields.MDTextField(verbose_name='文章内容')),
            ],
            options={
                'verbose_name': '课程',
                'verbose_name_plural': '课程',
                'db_table': 'all_course',
            },
        ),
    ]
